//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutfitName
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OutfitName()
        {
            this.OutfitParts = new HashSet<OutfitPart>();
        }
    
        public int OutfitID { get; set; }
        public string Name { get; set; }
        public string Season { get; set; }
        public string Occasion { get; set; }
        public int CharchterID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutfitPart> OutfitParts { get; set; }
        public virtual Charachter Charachter { get; set; }
    }
}
